### PR TITLE
added fasrhbzemail attribute

### LINKED ISSUE #288: Return the `fasrhbzemail` attribute of users
## Acceptance Criteria

* The `fasRHBZEmail` attribute value is returned when the user has set it

## Definition of Done

* AC is met
* Unit tests pass with 100% coverage
* Docs are updated

### PR DESCRIPTION
**Pull request by phsmoura**
Fixes [#288](https://github.com/fedora-infra/fasjson/issues/288)

## Proposed Changes

* Added `fasRHBZEmail` attribute to UserModel class 
* Added `fasRHBZEmail` attribute to unit tests to be mocked

## Verification Steps

* Runned `tox` to check if unit tests are passing and docs built

### CODE REVIEW

**Comment by abompard** [comment]
Looks good, could you add a news file [as described here](https://noggin-aaa.readthedocs.io/en/latest/contributing.html#release-notes) as well please? Also, please do your commit with `git commit -s` to add the `Signed-Off-By` line, it will clear the `DCO` check.

**Comment by phsmoura** [comment]
Done @abompard, sorry I missed that. I also put a description in the news file, is it right?

**Review by abompard — APPROVED** [review]

**Comment by abompard** [comment]
Apparently the coverage is not 100%, could you check it out please and add a test where needed?

**Comment by abompard** [comment]
@mergifyio refresh

**Pull request merged**
