### PR TITLE
Add an endpoint to sign a user's Certificate Signing Request

### LINKED ISSUE #28: As a CentOS packager, I want to get a certificate signed by the IPA CA so that I can access CentOS servers
CentOS uses x509 certificates to access build nodes, we need to provide a way for those users to get their certificates.

## Acceptance Criteria

* Users have an API endpoint to list the certificates they own (possibly using the `cert_find` IPA command)
* Users have an API endpoint to get their signed certificate if they have one (possibly using the `cert_show` IPA command).
* Users have an API endpoint to upload their CSR to (possibly using the `cert_request` IPA command)
* Depending on whether the CSR endpoint returns signed certificates directly or not, users may need an API endpoint to check the status of their certificate signing request (possibly using the `cert_status` IPA command)
* Those endpoints are authenticated like the rest of FASJSON, through Kerberos
* A user only has access to the certs they are allowed to see. It's usually only theirs, but people with elevated permissions may be allowed to see more, so we shouldn't assume that a user can only have one certificate.

For example, there could be:
- a `/certs/` namespace where certificates could be queried with `?users=<connected_user>`, calling `cert_find`
- a `/certs/<serial>` endpoint where a certificate would be retrieved with `cert_show`.
- a `/certs/request` endpoint where CSRs could be uploaded. It could return the signed certificate in a JSON dict, that would also contain the URL to that certificate in the API as a hyperlink.
Those are just suggestions. See fedora-infra/noggin#34 for the original request.

## Definition of Done

* All AC are done
* There is an OpenAPI spec describing the endpoints
* Hyperlinks are used to link results to endpoints
* There is documentation
* Unit test coverage is 100%

### PR DESCRIPTION
**Pull request by abompard**
Fixes #28

This set of commits adds user certificates to the existing user resource, and adds a new endpoint where users can upload their CSR to get it signed by IPA's CA.

This is only the server part, the client part will be in fasjson-client.

### CODE REVIEW

**Comment by StephenCoady** [comment]
@abompard would it be useful to also use `cert_find` to list all certificates the user owns? Or is there a reason you didn't add it?

**Comment by abompard** [comment]
Yeah user certificates are accessible directly from the user API representation now.

**Comment by StephenCoady** [comment]
OK cool, well I have no questions really. Its very clear what you are doing and easy to understand. There are conflicts so I can approve once they are merged

**Comment by abompard** [comment]
Thanks, rebased now. You can approve the PR before the tests are done running if you want to, and Mergify will merge it only when they pass.

**Pull request merged**
