### PR TITLE
Add rhbzemail as search argument

### LINKED ISSUE #370: As a user I want to be able to search users by bugzilla e-mail
Currently it's not possible to search by `rhbzemail` field and if the user in bugzilla has different mail than the FAS e-mail it can't be found directly.
For [scm_request_processor](https://pagure.io/fedora-infra/toddlers/blob/main/f/toddlers/plugins/scm_request_processor.py) toddler this is a way to map bugzilla account with concrete user in Bugzilla review ticket.

## Acceptance Criteria
* `fasjson` will allow search by `rhbzemail` field 

## Definition of Done
* PR is merged
* Change is deployed

### PR DESCRIPTION
**Pull request by Zlopez**
This commit adds `rhbzemail` as possible search argument for search API call.

Closes #370.

Signed-off-by: Michal Konečný <mkonecny@redhat.com>

### CODE REVIEW

**Review by abompard — APPROVED** [review]

**Comment by Zlopez** [comment]
About the error:
The `werkzeug` removed the `parse_rule` function in version newer than 2.1.2, I needed to [freeze it on this version on Anitya](https://github.com/fedora-infra/anitya/blob/master/requirements.txt#L19), to be able to build the docs.

**Comment by abompard** [comment]
I'll fix the coverage issue later. Please note that there are two ways of searching for the rhbz email:
- `rhbzemail=foo@bar.com`: will search for *substrings*, which may work identically, but is not as efficient
- `rhbzemail__exact=foo@bar.com`: will search for the exact string. Probably what you want to do.

**Comment by Zlopez** [comment]
@abompard I didn't know about `rhbzemail__exact`, so I didn't added it to arguments of search method. Does this mean I should create another PR for `rhbzemail_exact`?

Also how long till this will be available in staging?

**Comment by abompard** [comment]
No you don't need to do anything, all query arguments can be called with the `__exact` suffix (2 underscores) for an exact matching.

**Comment by abompard** [comment]
Oh, and I've pushed to staging, @Zlopez

**Pull request merged**
